### ISSUE TITLE
add op_cat use case series to 

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/awesome-op-cat#1]
https://github.com/sCrypt-Inc/awesome-op-cat?tab=readme-ov-file#technical
1-5 so far.
https://scryptplatform.medium.com/bitcoin-op-cat-use-cases-series-5-drivechain-e962ee227da5

**Comment by yusufidimaina9989** [comment]
done.

https://github.com/sCrypt-Inc/awesome-op-cat/pull/2
